### ISSUE TITLE
Exchange not Shown

### ISSUE THREAD

**Issue by sHaDoW8185** [MarcelBeining/EazeBot#1]
I have configured your telegram bot and added my API keys to the json files, as well as created a telegram bot.  The bot functions and I can communicate with it, but upon trying to check my account balance, it asks me what exchange I'd like to find the balance for.  No exchanges show up in the list.  I don't see any errors being thrown, so I am not sure where the bot is malfunctioning.

**Comment by MarcelBeining** [comment]
Hi and thanks for your interest in Eazebot.
It doesn't look like the API information was used. I need some more
information to find the possible problem:
1) When you start the bot in Python, there should be a message "Exchanges
[xxx] added/updated. Does it show anything between those two brackets? If
not it does not use the API keys given.
2) did you use the recommended way with the install/init Eazebot bat file
to install it or how did you do it exactly? Maybe the bot is not using your
configured APIs.json but the blank one.
3) what is your system?
4) Is there any error shown in the log file?
5) what Exchanges did you try to add?

jplkid14 <notifications@github.com> schrieb am Fr., 29. Juni 2018, 21:14:

**Comment by sHaDoW8185** [comment]
1) I don’t see it, see text output below. Also, I manually entered the same
info into both configuration files in both locations. Is it possible the
setup saw this and didn’t do something correctly?
2) Used installer batch file
3) Windows 10 x64, the latest build
4) See above
5) Binance only

C:\Users\sHaDoW\AppData\Local\Programs\Python\Python37-32\python.exe
"C:/Run/EazeBot 1.2.14/eazebot/startBotScript.py"
2018-06-29 12:06:27,566 [MainThread  ] [WARNI]  If 'per_message=False',
'CallbackQueryHandler' will not be tracked for every message.
2018-06-29 12:06:27,566 [MainThread  ] [WARNI]  If 'per_message=False',
'CallbackQueryHandler' will not be tracked for every message.
2018-06-29 12:06:27,566 [MainThread  ] [WARNI]  If 'per_message=False',
'CallbackQueryHandler' will not be tracked for every message.
2018-06-29 12:06:27,566 [MainThread  ] [WARNI]  If 'per_message=False',
'CallbackQueryHandler' will not be tracked for every message.
2018-06-29 12:06:27,566 [MainThread  ] [WARNI]  If 'per_message=False',
'CallbackQueryHandler' will not be tracked for every message.
2018-06-29 12:06:27,567 [MainThread  ] [INFO ]  Loading user data
2018-06-29 12:06:39,602 [dispatcher  ] [INFO ]  User Jacob Burbank-Goldrich
(username: jbgoldrich, id: 530658067) (re)started the bot
2018-06-29 12:06:53,363 [dispatcher  ] [ERROR]  An uncaught error was
raised while processing the update
Traceback (most recent call last):
  File
"C:\Users\sHaDoW\AppData\Local\Programs\Python\Python37-32\lib\site-packages\telegram\ext\dispatcher.py",
line 279, in process_update
    handler.handle_update(update, self)
  File
"C:\Users\sHaDoW\AppData\Local\Programs\Python\Python37-32\lib\site-packages\telegram\ext\conversationhandler.py",
line 305, in handle_update
    new_state = self.current_handler.handle_update(update, dispatcher)
  File
"C:\Users\sHaDoW\AppData\Local\Programs\Python\Python37-32\lib\site-packages\telegram\ext\regexhandler.py",
line 173, in handle_update
    return self.callback(dispatcher.bot, update, **optional_args)
  File "C:\Run\EazeBot 1.2.14\eazebot\EazeBot.py", line 424, in addExchanges
    APIs = json.load(fin)
  File
"C:\Users\sHaDoW\AppData\Local\Programs\Python\Python37-32\lib\json\__init__.py",
line 296, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook,
**kw)
  File
"C:\Users\sHaDoW\AppData\Local\Programs\Python\Python37-32\lib\json\__init__.py",
line 348, in loads
    return _default_decoder.decode(s)
  File
"C:\Users\sHaDoW\AppData\Local\Programs\Python\Python37-32\lib\json\decoder.py",
line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File
"C:\Users\sHaDoW\AppData\Local\Programs\Python\Python37-32\lib\json\decoder.py",
line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double
quotes: line 4 column 1 (char 179)
2018-06-29 12:07:27,569 [job_queue   ] [INFO ]  Updating trade sets...
2018-06-29 12:07:27,569 [job_queue   ] [INFO ]  Finished updating trade
sets...
2018-06-29 12:07:27,570 [job_queue   ] [WARNI]  No backup file found
2018-06-29 12:07:27,571 [job_queue   ] [INFO ]  Created user data autosave
backup
2018-06-29 12:07:27,586 [job_queue   ] [INFO ]  User data autosaved
2018-06-29 12:08:04,520 [dispatcher  ] [INFO ]  User Jacob Burbank-Goldrich
(username: jbgoldrich, id: 530658067) (re)started the bot
2018-06-29 12:08:27,568 [job_queue   ] [INFO ]  Updating trade sets...
2018-06-29 12:08:27,568 [job_queue   ] [INFO ]  Finished updating trade
sets...
2018-06-29 12:09:27,568 [job_queue   ] [INFO ]  Updating trade sets...
2018-06-29 12:09:27,568 [job_queue   ] [INFO ]  Finished updating trade
sets...
2018-06-29 12:10:05,351 [dispatcher  ] [ERROR]  An uncaught error was
raised while processing the update
Traceback (most recent call last):
  File
"C:\Users\sHaDoW\AppData\Local\Programs\Python\Python37-32\lib\site-packages\telegram\ext\dispatcher.py",
line 279, in process_update
    handler.handle_update(update, self)
  File
"C:\Users\sHaDoW\AppData\Local\Programs\Python\Python37-32\lib\site-packages\telegram\ext\conversationhandler.py",
line 305, in handle_update
    new_state = self.current_handler.handle_update(update, dispatcher)
  File
"C:\Users\sHaDoW\AppData\Local\Programs\Python\Python37-32\lib\site-packages\telegram\ext\regexhandler.py",
line 173, in handle_update
    return self.callback(dispatcher.bot, update, **optional_args)
  File "C:\Run\EazeBot 1.2.14\eazebot\EazeBot.py", line 424, in addExchanges
    APIs = json.load(fin)
  File
"C:\Users\sHaDoW\AppData\Local\Programs\Python\Python37-32\lib\json\__init__.py",
line 296, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook,
**kw)
  File
"C:\Users\sHaDoW\AppData\Local\Programs\Python\Python37-32\lib\json\__init__.py",
line 348, in loads
    return _default_decoder.decode(s)
  File
"C:\Users\sHaDoW\AppData\Local\Programs\Python\Python37-32\lib\json\decoder.py",
line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File
"C:\Users\sHaDoW\AppData\Local\Programs\Python\Python37-32\lib\json\decoder.py",
line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double
quotes: line 4 column 1 (char 179)

**Comment by sHaDoW8185** [comment]
Tried re-installing my python 3.7 into Program Files(x86) and ran you bat installer (after cleaning out all folders and remaining trash as well as clearing environmental variables that called to the old python location).  The installer downloaded all the necessary required files and ran ONCE.  Upon terminating the bot (which still could not connect to exchanges throwing the above errors) I now get this error:

c:\Run\EazeBot 1.2.14>py startbotscript.py
2018-06-29 21:50:23,005 [MainThread  ] [WARNI]  If 'per_message=False', 'CallbackQueryHandler' will not be tracked for every message.
2018-06-29 21:50:23,005 [MainThread  ] [WARNI]  If 'per_message=False', 'CallbackQueryHandler' will not be tracked for every message.
2018-06-29 21:50:23,006 [MainThread  ] [WARNI]  If 'per_message=False', 'CallbackQueryHandler' will not be tracked for every message.
2018-06-29 21:50:23,006 [MainThread  ] [WARNI]  If 'per_message=False', 'CallbackQueryHandler' will not be tracked for every message.
2018-06-29 21:50:23,006 [MainThread  ] [WARNI]  If 'per_message=False', 'CallbackQueryHandler' will not be tracked for every message.
2018-06-29 21:50:23,006 [MainThread  ] [INFO ]  Loading user data
An error occured:
Expecting property name enclosed in double quotes: line 4 column 1 (char 179)

**Comment by sHaDoW8185** [comment]
I have played around some more and am realizing that there is an issue with the way information is stored in your data.pickle file (or surrounding data manipulation).  If I run the bot once, when no data.pickle file is present...the code executes, throwing me some errors saying that it can't load the backup file (makes sense, there isn't one yet).   However, after terminating the bot and reloading it, at some point the data.pickle file was created to store information.  Upon reloading the bot after first run, these error messages come up expecting property name enclosed in double quotes.

I am no python expert in any way, but when I load your code in Pycharms, it mentions many PEP space inconsistencies, as well as Single/Double quote flags and upper/lowercase misuses for functions, etc.

I don't know if all this comes together to produce these issues, but it definitely seems like something needs to be standardized to follow the Python 3.7 decoder/interpreter rules and referencing practices. 

I hope all of this helps, and sorry for the spamming of all this information on the page.

**Comment by MarcelBeining** [comment]
Hi,
the error Python gives to you that is "Expecting property name enclosed in double
quotes" refers not to my code but to your json file.
It seems you have a comma at the end near of your APIs.json which should not be there. If you only have one exchange added, make sure to have deleted that comma in the last line, like:
{
  "apiKeyBinance": "kasdhiuashiuxnjkcnasskjndjkajshkjdsahjkas",
  "apiSecretBinance": "aishdiuashasdasdukdhakhdkadaskkashkjash"
}

**Comment by sHaDoW8185** [comment]
Well...I feel stupid lol.  Thank you!

**Comment by sHaDoW8185** [comment]
Thinking further, though...I had this:

{
  "telegramAPI": "askljdflkasdjfaslkjdfaslkdjfaslkdjfaslkdjf",
  "telegramUserId": "9999999",
  "updateInterval": 1
}

Which means I didn't have a comma in my last line...

**Comment by sHaDoW8185** [comment]
I deleted the comment, realizing the error of my noobish ways.
