### ISSUE TITLE
Kucoin - how to define the KC-API-PASSPHRASE in APIs.json

### ISSUE THREAD

**Issue by offtopic** [MarcelBeining/EazeBot#10]
The v2 API of Kucoin requires a pass phrase: KC-API-PASSPHRASE
https://docs.kucoin.com/#permissions
If I add apiKeyKucoin + apiSecretKucoin I get the following error:

> 2019-05-23 07:02:09,915 [dispatcher  ] [WARNI]  Authentication failed for kucoin
> error: Failed to authenticate at exchange KuCoin. Please check your keys

Is it possible to configure the required passphrase for kucoin?
Best regards!

**Comment by MarcelBeining** [comment]
Sure! Simply add a line in the APIs.json :

"apiPasswordKucoin": "yourpassword"

Don't forget the comma such that behind all lines that define some secret/password/key except the last line there is a comma.

**Comment by offtopic** [comment]
This was a easy one ;)
Thank you very much 😀

Am Sa., 25. Mai 2019 um 09:59 Uhr schrieb Marcel Beining <
notifications@github.com>:
