### ISSUE TITLE
Delete an old trade set

### ISSUE THREAD

**Issue by stevan117** [MarcelBeining/EazeBot#18]
**Describe the bug**
Thanks for a fantastic program, few have the features and exchanges you have included.
On Button 'Status of Trade Sets', a old trade set is shown, I ask to delete, without selling coins, and Telegram report nothing, but File "/usr/local/lib/python3.6/dist-packages/eazebot/tradeHandler.py", line 471, in create_trade_history_entry
    'days': None if 'createdAt' not in ts
TypeError: argument of type 'BaseTradeSet' is not iterable

**To Reproduce**
1. Go to 'Status of Trade sets'
2. Click on 'either Delete or Edit Delete'
3. Sell Coins  'No'
4. Delete Trade Set 'Yes' = in Putty = iterable error in tradeHandler.py", line 471

**Expected behavior**
I am hoping to clear the trade set.

Thanks Again
Steven

**Comment by MarcelBeining** [comment]
Thanks for reporting and the compliment :-)

I fixed the bug in [v2.7.1](https://github.com/MarcelBeining/EazeBot/releases/tag/v2.7.1)
