### ISSUE TITLE
Mis Calculation

### ISSUE THREAD

**Issue by weindler** [MarcelBeining/EazeBot#4]
Hello Eazybot is installed on an AWS server. I noticed that something is wrong with the bill.
See the screenshot.
If I want to open another sell level then the open coins do not match.
See screenshot.Thank you for your help.
![rechenfehler bnb 1](https://user-images.githubusercontent.com/41335851/43673808-45acb1de-97c9-11e8-99c4-f557211fb023.JPG)
![rechenfehler bnb 2](https://user-images.githubusercontent.com/41335851/43673809-45c9e8a8-97c9-11e8-8768-c097d0a299e0.JPG)
Hallo Eazybot ist auf einem AWS Server installiert. Mir ist aufgefallen, dass irgendwas mit der Rechnung nicht stimmen kann.
Siehe Screenshot.
Wenn ich nun einen weiteren Sell Level eröffnen will dann stimmen die offenen Coins nicht überein. 
Siehe Screenshot.Danke für deine Hilfe

**Comment by MarcelBeining** [comment]
Hi, you are right, there was a bug such that the coins that are already in sell are subtracted twice! New Version 1.6.2 should fix it! Thanks for reporting!
