### ISSUE TITLE
After the update to 1.6.4 there are some errors in the ssh panel

### ISSUE THREAD

**Issue by weindler** [MarcelBeining/EazeBot#5]
ubuntu@ip-:~/eazebot$ 2018-08-06 13:07:01,051 [job_queue   ] [ERROR]  User : <class 'ccxt.base.errors.InvalidOrder'> in tradeHandler.py at line 112: binance {"code":-1013,"msg":"Filter failure: MIN_NOTIONAL"}
bash: class: No such file or directory
ubuntu@ip-:~/eazebot$ 2018-08-06 13:07:01,071 [job_queue   ] [WARNI]  Some connection (?) error occured
bash: syntax error near unexpected token `('
ubuntu@ip-:~/eazebot$ 2018-08-06 13:07:02,092 [job_queue   ] [WARNI]  Some connection (?) error occured
bash: syntax error near unexpected token `('
ubuntu@ip-1:~/eazebot$ 2018-08-06 13:07:03,114 [job_queue   ] [WARNI]  Some connection (?) error occured
bash: syntax error near unexpected token `('
ubuntu@ip-:~/eazebot$ 2018-08-06 13:07:04,135 [job_queue   ] [WARNI]  Some connection (?) error occured
bash: syntax error near unexpected token `('
ubuntu@ip-:~/eazebot$ 2018-08-06 13:07:05,157 [job_queue   ] [WARNI]  Some connection (?) error occured
bash: syntax error near unexpected token `('
ubuntu@ip-1:~/eazebot$ 2018-08-06 13:07:06,158 [job_queue   ] [ERROR]  Could not send message to bot
2018-08-06: command not found
ubuntu@ip-1:~/eazebot$ 2018-08-06 13:07:06,159 [job_queue   ] [ERROR]  binance {"code":-1013,"msg":"Filter failure: MIN_NOTIONAL"}
2018-08-06: command not found
ubuntu@ip-:~/eazebot$ 2018-08-06 13:07:06,159 [job_queue   ] [INFO ]  Finished updating trade sets...
2018-08-06: command not found
ubuntu@ip-:~/eazebot$

On the old version it hasn´t any error.
Please fix it, thanks

Greets Josef

**Comment by MarcelBeining** [comment]
Info for all:
During private chat we found out that the origin of this was not the new version but an old sell order that was not yet subjected to the amount/price filter implemented in version 1.3.0 and thus elicited the error.
Nevertheless, I found out that a stop loss that triggers could still produce an order with a a too low amount (of remaining coins to sell) such that the exchange rejects the order. I will fix this bug in the next version
